name = "cloud"
type = "webpack"
workers_dev = true
account_id = "f265e53bab7510fbdf0148d022445bbb"
#zone_id = ""
kv_namespaces = [
    { binding = "BUCKET", preview_id = "0f422a115ffb43f986fcc4fb7b35384c", id = "7fd08768c2c94b47b8e4a953e56657b6" }
]

[env.staging]
name = "drive-staging"
