name = "cloud"
type = "webpack"
workers_dev = true
account_id = "f265e53bab7510fbdf0148d022445bbb"
#zone_id = ""
#kv_namespaces = [
#    { binding = "BUCKET", preview_id = "55b0fc4e288a465fb225421f2af5d445", id = "09b0cf433f394b309d35d1ff3bd0bf39" }
#]

[env.staging]
name = "drive-staging"
